import { randomUUID } from "node:crypto";
import { runAdaptation, type AdaptationInput } from "@/lib/adaptation/pipeline";
import { saveAdaptation } from "@/lib/repositories/adaptation-repository";
export type WorkflowStatus = { workflowId: string; requestId: string; adaptationId: string; currentStage: string; status: "completed" | "blocked"; startedAt: string; finishedAt: string; durationMs: number };
export interface WorkflowRunner { run(input: AdaptationInput): Promise<{ result: ReturnType<typeof runAdaptation>; workflow: WorkflowStatus; persisted: { persisted: boolean; reason?: string; adaptationId?: string } }> }
export class RenderWorkflowRunner implements WorkflowRunner { constructor(private readonly endpoint: string) {} async run(input: AdaptationInput) { const response = await fetch(this.endpoint, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ workflow: "adaptContentWorkflow", input }) }); if (!response.ok) throw new Error(`Render workflow failed with ${response.status}`); return await response.json() as Awaited<ReturnType<LocalWorkflowRunner["run"]>>; } }
export class LocalWorkflowRunner implements WorkflowRunner { async run(input: AdaptationInput) { return adaptContentWorkflow(input); } }
export async function adaptContentWorkflow(input: AdaptationInput) { const started = Date.now(); const startedAt = new Date(started).toISOString(); const result = runAdaptation(input); const persisted = !result.blocked ? await saveAdaptation({ content: input.content, mode: input.mode, result }) : { persisted: false as const, reason: "safety_blocked" }; const finished = new Date().toISOString(); return { result, persisted, workflow: { workflowId: `local-${randomUUID()}`, requestId: randomUUID(), adaptationId: randomUUID(), currentStage: result.blocked ? "safetyScan" : "buildDecisionReceipt", status: result.blocked ? "blocked" : "completed", startedAt, finishedAt: finished, durationMs: Date.now() - started } satisfies WorkflowStatus }; }
export function getWorkflowRunner(): WorkflowRunner { return process.env.WORKFLOW_PROVIDER === "render" && process.env.RENDER_WORKFLOW_URL ? new RenderWorkflowRunner(process.env.RENDER_WORKFLOW_URL) : new LocalWorkflowRunner(); }
